# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - data-mining

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f77f1f354fba436bb1c48a25e20ebda6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7d2517fffb344b44b558078536e978c4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f77f1f354fba436bb1c48a25e20ebda6 }}/ninjaasmoke/data-mining:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'data-mining'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_212b267836364380bb6207637ffc2ede }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f77f1f354fba436bb1c48a25e20ebda6 }}/ninjaasmoke/data-mining:${{ github.sha }}'